apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: prod

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readonly-essentials
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints","configmaps","namespaces"]
    verbs: ["get","list","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments","replicasets","daemonsets","statefulsets"]
    verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-devs-readonly
subjects:
  - kind: Group
    name: oidc:devs               # map this via aws-auth + OIDC
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: readonly-essentials

